### ISSUE TITLE
second Multiplus?

### ISSUE THREAD

**Issue by Starter4711** [mr-manuel/venus-os_dbus-multiplus-emulator#2]
Hello,
I have 3P ESS with MP2 5k and Gobel Packs. 
A second 3P ESS wirh MP2 5k just to additionally load the Batteries from a second Source. Each system has a Cerbo. 

Would it be possible to get the second MP into the first VRM system with your plugin?

First I just want show the VRM, there is a Charger on the battery. 
Second the Cerbo should reduce the Charging Limits of first MP with the value of the second MP. 

If there are not two MP in one VRM system allowed, maybe a virtual MPPT?

Thanks

**Comment by mr-manuel** [comment]
Unfortunately I don't know how it looks like, when there are two or three MultiPlus or Quattro connected to one Venus OS device.

I don't think to alter the system values, because it can lead to system instability, since the system think it's loading with 40 amps, but in real it's only loading with 10 amps.

**Comment by Starter4711** [comment]
Thanks for your response. 

It would  just be an additional Info to VRM like a MPPT , the BMS Shows up the Limits for the MP2, that Will Not be a conflict.

**Comment by mr-manuel** [comment]
Are you sure? I'm not. Why don't you just add the other MultuPlus to a separate instance of the VRM portal?

A MPPT is a additional device, a MultiPlus is the hearth of the system, which connects DC with AC and vice versa. The MutliPlus therefore also controlls how much current flows in which direction, which in the worst case, could also cause damage.

Sorry, but I won't do this.
