### ISSUE TITLE
Critical Load showing leading to wrong AC Loads

### ISSUE THREAD

**Issue by mhin76** [mr-manuel/venus-os_dbus-multiplus-emulator#5]
great service! I just installed it. I discovered that it shows a critical load, not sure where that number is coming from. That value is added to AC Loads showing incorrect AC Load and Grid Load. Is there a config I am missing?
<img width="431" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/28fc0e3a-3564-42f8-83b0-b71ffba87801">

**Comment by mhin76** [comment]
Update: I added all three phases on the config file, showing now all three:
<img width="172" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/bedcb9ff-5aa0-4ab0-be5f-4754881dbf72">
my idea first was to not select any phases, but phase 1 (L1) stays with latest value. next idea was now I only select phase 3, as that one is 0. but phase 1 (L1) is then sill listed. So only possibility currently I would have is to wait until L1 is 0, then take out all phases. should be possible once night approaches.

**Comment by mhin76** [comment]
and last update: when selecting L3 (which is 0, because no inverter is attached to that phase) it just takes some time to have the critical load reduced to 0 as well! so that approach works for me.
<img width="518" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/79f8056b-e858-4283-8e8d-e9368c793ce0">

I will close this issue. hope it helps others that have similar challenge.

**Comment by mhin76** [comment]
sorry, for back and forth, just see when selecting L3 the sum is not correct. there is usage from Grid, but AC Loads does not show anything. when selectin L1, then L3 AC load is correct, but critical load is then again messing up the AC load.

**Comment by mr-manuel** [comment]
I'm not using it anymore, therefore I have no feedback for you. Can you post your configuration, if someone else has the same issue?

**Comment by mhin76** [comment]
I still have only on VRM a load on L2, even critical load is all 0 on remote console page. I will play a bit more around this evening when there is no inverter power. But I like your code a lot! thanks for sharing!
only config change I did was setting the phase to ="L4". more update later on.

**Comment by mhin76** [comment]
I found the solution. all working fine for me now. I set the phase to L4 but also needed to turn off the critical load on the simulated ESS:
<img width="396" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/55975aab-fc79-4264-b30e-295625c0176a">

all figures are correct and all data seem to be correct:
<img width="447" alt="image" src="https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/81155058-c659-4aad-81f8-b0da4105bdf6">
