### ISSUE TITLE
Use MultiPlus Control on VRM

### ISSUE THREAD

**Issue by mhin76** [mr-manuel/venus-os_dbus-multiplus-emulator#6]
Hi Manuel
great driver, works seemlessly with the dbus-mqtt-battery one. 
Not an issue, but rather a new requirement.
As I am controlling the battery charging via nodered (daly BMS) I wonder if there is any chance to get the input from this emulated multiplus on VRM back e.g. to e.g. MQTT. E.g. controls like battery charge on/off, min SOC %, max current limit.
Kind regards,
Martin

**Comment by mr-manuel** [comment]
Sorry, I can't completely understand what you need. Since the MultiPlus is emulated you cannot change the On/Off/Invert only/Charge only switch, since it has no action.

**Comment by mhin76** [comment]
It would be great if the control input on VRM about battery is somehow getting back to the emulated driver and maybe stored on MQTT, I am using NodeRed and the dbus-mqtt-battery to steer charging/uncharging.
![image](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/d46d8d30-dd55-4135-a7f5-fb7022d0bd9c)

not sure if VRM is sending anything back to your multiplus emulator.

**Comment by mhin76** [comment]
update: I think those settings I should get out from the dedicated Venus OS netatmo nodes :-) will keep it updated here.

**Comment by mr-manuel** [comment]
Are you using the latest version of this driver? I made some tests and if you change the settings in VRM, it changes also on Venus OS.

![venus-os-multiplus-emulator](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/12592765/4b4a888d-d831-4665-8992-077ef3317747)

**Comment by mhin76** [comment]
nice, with gif :-) very convenient!
that is aligned, the changes on the vrm control and the venus OS. what I did not manage yet is to get the setting out via NodeRed venus nodes. I can select the MultiPlus (emulated) but the values to get out are very limited:
![image](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/8fc2aa69-0533-4a8c-a198-0718dec26e2d)

but it is low priority! as I can also steer it via iPhone using Homebridge switches.

**Comment by mr-manuel** [comment]
You are using the wrong node. This has nothing to do with ESS. Use the `Ve.Bus System` node.

**Comment by mhin76** [comment]
Thank you so much Manuel for you support. That was it!! Works 😀💪🏼

**Comment by mr-manuel** [comment]
Feel free to buy me a beer on this hot days 😎

**Comment by mhin76** [comment]
@mr-manuel happy to do so, just via donation paypal charges 10%! :-o if you send my your IBAN on buymeabeer@hinz.ch I am happy to transfer there without charges :-)

**Comment by mr-manuel** [comment]
Not via family & friends, there is no fee: https://paypal.me/mrmanuel3

**Comment by mhin76** [comment]
not for me from Switzerland, they want even over 30% of fee :-( last time my donation was also via IBAN to another home automation guy. 
![image](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/41666e60-4037-4fb0-82d6-6c85f84ebb23)

**Comment by mr-manuel** [comment]
Then don't worry :)

**Comment by mhin76** [comment]
ok, would have loved to buy you some beers. :-)

**Comment by mhin76** [comment]
der Wille war da, via Donation, da kostet es nur 10% Gebühr. Versuche es später nochmals. Weiss nicht, was falsch geht.
![image](https://github.com/mr-manuel/venus-os_dbus-multiplus-emulator/assets/49210075/382e9d33-a204-4f71-b4f0-365b38305fe4)

**Comment by mr-manuel** [comment]
Very odd. Thanks again
