### ISSUE TITLE
no issue feature request#1

### ISSUE THREAD

**Issue by cyclemat** [mr-manuel/venus-os_dbus-multiplus-emulator#9]
can you make the feature to add mqtt to the emulator so we can put in other sources that create input to the grind ? ore something else  and a virtual mppt was the hit so we can use other mppts an read them out und send to the system

**Comment by mr-manuel** [comment]
Check my repository, there is everything you need.

**Comment by pellenbeck** [comment]
I would also think the addition of MQTT for supplying external performance data would be great.
I would like to integrate an old hybrid inverter into my Victron system (MP2GX & MP2 on L1 & L2), which hangs on the AC in loads to integrate the PV power and the battery (SOC, charging/discharging power).

Currently, I have only integrated the pure PV power via venus-os_dbus-mqtt-pv. Charging the battery (no 48V, no voltage data available) is therefore currently calculated in the AC loads of the Venus OS, which actually distorts the consumption values. The same leads to the problem that the consumption values are reduced when the battery is discharged.
